[build]
  base = "Frontend"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"
    Strict-Transport-Security = "max-age=31536000"

[build.environment]
  NODE_VERSION = "20"
